<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    
    <Authors>Etherna SA</Authors>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EthernaSdk.Internal.AspNetCore\EthernaSdk.Internal.AspNetCore.csproj" />
  </ItemGroup>

</Project>
